# SPDX-License-Identifier: MIT

list(APPEND PBLE_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/src/common.c)

if(PBLE_TARGET_PLATFORM STREQUAL dummy)
	list(APPEND PBLE_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/src/dummy.c)
elseif(PBLE_TARGET_PLATFORM STREQUAL esp32)
	list(APPEND PBLE_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/src/esp32.c)
elseif(PBLE_TARGET_PLATFORM STREQUAL nrf52)
	list(APPEND PBLE_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/src/nrf52.c)
elseif(PBLE_TARGET_PLATFORM STREQUAL zephyr)
	list(APPEND PBLE_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/src/zephyr.c)
else()
	message(FATAL_ERROR "No target specified.")
endif()

list(APPEND PBLE_INCS ${CMAKE_CURRENT_SOURCE_DIR}/include)
